import { Loading } from "@/components/helpers/loading";
import Splash from '@/components/layout/Splash';
import Popup from "../components/helpers/popup";
import Providers from "@/services/Providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import "@/styles/fonts.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "yadakYar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ToastContainer
            progressStyle={{
              background:
                "linear-gradient( to right, rgb(255, 177, 177), rgb(255, 60, 60))",
            }}
            style={{
              marginTop: "50px",
              padding: "20px",
              right: 0,
              fontFamily: "Yekan Bakh",
            }}
          />
          <Splash/>
          {children}
          <Popup />
          <Loading />
        </Providers>
      </body>
    </html>
  );
}
